server:
  port: 8080
  tomcat:
    max-swallow-size: 500MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phu
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    elasticsearch:
      rest:
        uris: http://localhost:9200
      repositories:
        enabled: true
  servlet:
    session:
      timeout: 30m
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.multipart: DEBUG

file:
  upload-dir: C:/Users/Phu Nguyen/Desktop/uploads

vnpay:
  tmnCode: MKVORUGQ
  hashSecret: B8NEDBJY4FVGAXJT2GXKPHMH0MZ6I8DY
  paymentUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:8080/api/v1/payment/vnpay-payment-return
